import React from 'react';
import { ScanResult } from '../types';
import { ShieldCheck, Printer, X, FileText, CheckCircle2, Lock, Scale, AlertOctagon } from 'lucide-react';

interface AuditCertificateModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: ScanResult;
}

export const AuditCertificateModal: React.FC<AuditCertificateModalProps> = ({
  isOpen,
  onClose,
  result
}) => {
  if (!isOpen) return null;

  const isCriminal = result.threatLevel === 'CRITICAL' || result.threatLevel === 'HIGH';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
      <div className="relative w-full max-w-2xl bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl flex flex-col overflow-hidden max-h-[90vh]">
        {/* Header */}
        <div className="p-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-1.5 rounded-lg bg-cyan-500/20 text-cyan-400">
              <Lock className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-xs font-bold text-white font-mono uppercase tracking-wider">
                Cryptographic Evidentiary Audit Certificate
              </h3>
              <p className="text-[10px] text-slate-400 font-mono">
                Tamper-Evident Security Dossier for Law Enforcement &amp; Bank Dispute
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-mono font-semibold transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Printable Certificate Body */}
        <div className="p-6 overflow-y-auto space-y-5 bg-slate-950/60 font-mono">
          {/* Certificate Banner */}
          <div className="p-4 rounded-xl border border-cyan-500/30 bg-slate-950 text-center space-y-1 relative">
            <div className="text-[10px] uppercase tracking-widest text-cyan-400 font-bold">
              OFFICIAL INCIDENT DOSSIER
            </div>
            <h2 className="text-base font-extrabold text-white">
              PHISHING &amp; ADVANCE-FEE FRAUD AUDIT CERTIFICATE
            </h2>
            <p className="text-[11px] text-slate-400">
              Generated by Sentinel PhishGuard AI Cyber Threat Intelligence
            </p>

            <div className="mt-2 text-[10px] text-slate-500 break-all bg-slate-900/80 p-2 rounded border border-slate-800">
              <strong>CRYPTOGRAPHIC FINGERPRINT:</strong> {result.hashFingerprint}
            </div>
          </div>

          {/* Audit Metrics */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
            <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
              <span className="text-[10px] text-slate-400 block">THREAT INDEX</span>
              <strong className={`text-base ${result.threatIndex >= 75 ? 'text-rose-400' : 'text-emerald-400'}`}>
                {result.threatIndex}%
              </strong>
            </div>
            <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
              <span className="text-[10px] text-slate-400 block">STATUS TIER</span>
              <strong className="text-xs text-white">{result.threatLevel}</strong>
            </div>
            <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
              <span className="text-[10px] text-slate-400 block">CATEGORY</span>
              <strong className="text-xs text-white">{result.targetType}</strong>
            </div>
            <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800">
              <span className="text-[10px] text-slate-400 block">EXPOSURE</span>
              <strong className="text-xs text-rose-400">${result.blastRadius.totalExposure.toLocaleString()}</strong>
            </div>
          </div>

          {/* 7-Step Authentication Pipeline Status */}
          {result.authPipeline && result.authPipeline.length > 0 && (
            <div className="space-y-1.5">
              <span className="text-[10px] uppercase font-bold text-cyan-400 tracking-wider block">
                7-Step Authentication Gate Verification Audit
              </span>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-1.5 max-h-36 overflow-y-auto">
                {result.authPipeline.map((step) => (
                  <div
                    key={step.id}
                    className={`p-1.5 rounded-lg border text-[10px] flex items-center justify-between ${
                      step.status === 'FAILED'
                        ? 'bg-red-950/40 border-red-900/60 text-red-300'
                        : step.status === 'SUSPICIOUS'
                        ? 'bg-amber-950/40 border-amber-900/60 text-amber-300'
                        : 'bg-emerald-950/40 border-emerald-900/60 text-emerald-300'
                    }`}
                  >
                    <span className="font-bold truncate max-w-[170px]">
                      {step.stepNumber}. {step.name.split(' ')[0]} {step.name.split(' ')[1] || ''}
                    </span>
                    <span className="font-mono font-bold text-[9px] uppercase shrink-0">
                      {step.status === 'FAILED' ? '❌ FAILED' : step.status === 'SUSPICIOUS' ? '⚠️ FLAG' : '✅ PASS'}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Legal / Statutory Classifications */}
          {isCriminal && (
            <div className="p-3 rounded-xl bg-slate-900 border border-slate-800 space-y-2">
              <div className="flex items-center gap-1.5 text-xs font-bold text-amber-300">
                <Scale className="w-4 h-4 text-amber-400" />
                <span>Applicable Federal / Statutory Fraud Violations</span>
              </div>
              <ul className="text-[11px] text-slate-300 space-y-1 list-disc list-inside">
                <li><strong>18 U.S.C. § 1343:</strong> Wire Fraud via interstate communications &amp; digital money transfers.</li>
                <li><strong>18 U.S.C. § 1344:</strong> Bank Fraud &amp; Counterfeit Negotiable Instruments (Fake Cashier's Checks).</li>
                <li><strong>18 U.S.C. § 1028:</strong> Fraud and Related Activity in Connection with Identification Documents.</li>
              </ul>
            </div>
          )}

          {/* Primary Evidence Findings */}
          <div className="space-y-2">
            <span className="text-[10px] uppercase font-bold text-slate-400 tracking-wider block">
              Forensic Red Flag Summary ({result.redFlags.length} Triggers)
            </span>
            <div className="space-y-1.5 max-h-40 overflow-y-auto">
              {result.redFlags.map((flag, idx) => (
                <div key={idx} className="p-2 rounded bg-slate-900 border border-slate-800 text-[11px]">
                  <div className="flex items-center justify-between font-bold text-slate-200">
                    <span>{flag.title}</span>
                    <span className="text-[9px] uppercase px-1 rounded bg-slate-800 text-slate-400">
                      {flag.severity}
                    </span>
                  </div>
                  {flag.flaggedText && (
                    <div className="text-[10px] text-slate-400 italic mt-0.5 truncate">
                      Quote: &ldquo;{flag.flaggedText}&rdquo;
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Footer Seal */}
          <div className="pt-3 border-t border-slate-800 flex items-center justify-between text-[10px] text-slate-500">
            <span>Verified by Sentinel AI Defense Matrix</span>
            <span>Timestamp: {new Date(result.analyzedAt).toUTCString()}</span>
          </div>
        </div>
      </div>
    </div>
  );
};
